name: 'parse-lighthouse-report-to-md'
description: 'Read Lighthouse report files and parse to markdown string'
author: 'kurly'
inputs:
  URL_LIST_JSON_STRING:
    required: true
    description: 'URL-LABEL Dataset'

  REPORT_DIR_NAME:
    required: true
    description: 'Report dir name'

  S3_BUCKET_NAME:
    required: true
    description: 'S3 Bucket name'

  AWS_ACCESS_KEY_ID:
    required: true
    description: 'AWS Access key id'

  AWS_SECRET_ACCESS_KEY:
    required: true
    description: 'AWS Secret Access key'

outputs:
  REPORT_MD_STRING:
    description: 'Markdown string'

runs:
  using: 'node16'
  main: 'dist/index.js'
