type InputNameType =
  | 'URL_LIST_JSON_STRING'
  | 'REPORT_DIR_NAME'
  | 'ASSERTION_DIR_NAME'
  | 'GH_TOKEN'
  | 'IMAGE_REPO_NAME'
  | 'IMAGE_REPO_OWNER_NAME'

const InputName: Record<InputNameType, InputNameType> = {
  URL_LIST_JSON_STRING: 'URL_LIST_JSON_STRING',
  REPORT_DIR_NAME: 'REPORT_DIR_NAME',
  ASSERTION_DIR_NAME: 'ASSERTION_DIR_NAME',
  GH_TOKEN: 'GH_TOKEN',
  IMAGE_REPO_NAME: 'IMAGE_REPO_NAME',
  IMAGE_REPO_OWNER_NAME: 'IMAGE_REPO_OWNER_NAME'
}

export default InputName
