type InputNameType =
  | 'URL_LIST_JSON_STRING'
  | 'REPORT_DIR_NAME'
  | 'S3_BUCKET_NAME'
  | 'AWS_ACCESS_KEY_ID'
  | 'AWS_SECRET_ACCESS_KEY'

const InputName: Record<InputNameType, InputNameType> = {
  URL_LIST_JSON_STRING: 'URL_LIST_JSON_STRING',
  REPORT_DIR_NAME: 'REPORT_DIR_NAME',
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
}

export default InputName
