name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          URL_LIST_JSON_STRING: '[{"label":"홈","path":"/","pathSlug":"_","url":"http://localhost:3000/"},{"label":"포스트","path":"/posts","pathSlug":"_posts","url":"http://localhost:3000/posts"}]'
          REPORT_DIR_NAME: 1
          S3_BUCKET_NAME: kurly-lighthouse-ci
          AWS_ACCESS_KEY_ID: 1
          AWS_SECRET_ACCESS_KEY: 1